"""
Smart Grid Edge AI — Solar Generation Prediction Model (model2.py)
==================================================================
Trains the base solar generation forecasting model.

Modified for Continuous Online Learning:
  - Uses SGDRegressor.
  - Reuses the StandardScaler from model.py to ensure 
    input vectors are identical.
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import joblib
import warnings
warnings.filterwarnings('ignore')

from model import (
    DATASET_URL,
    FORECAST_HORIZON,
    fetch_and_engineer_features,
)


def train_solar_model(df):
    df['target_solar_gen_1h'] = df['solar_gen_kw'].shift(-FORECAST_HORIZON)
    df = df.dropna()

    feature_cols = [
        'gross_demand_kw', 'ambient_light_lux', 'temperature_c', 'cloud_cover',
        'lagged_net_load_1h', 'lagged_solar_1h',
        'rolling_avg_net_load_24h', 'rolling_avg_net_load_7d',
        'hour_sin', 'hour_cos', 'is_weekend'
    ]

    X = df[feature_cols]
    y = df['target_solar_gen_1h']

    split_idx = int(len(df) * 0.8)
    X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
    y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]

    print("[*] Loading Scaler generated by model.py...")
    scaler = joblib.load('transformer_scaler.pkl')
    X_train_scaled = scaler.transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    print("[*] Training Solar SGDRegressor...")
    model = SGDRegressor(
        loss='squared_error',
        penalty='l2',
        alpha=0.0001,
        learning_rate='constant',
        eta0=0.0001,
        max_iter=1000,
        tol=1e-3,
        random_state=42
    )

    model.fit(X_train_scaled, y_train)
    predictions = model.predict(X_test_scaled)

    print(f"  MAE  : {mean_absolute_error(y_test, predictions):.4f} kW")
    print(f"  RMSE : {np.sqrt(mean_squared_error(y_test, predictions)):.4f} kW")
    print(f"  R²   : {r2_score(y_test, predictions):.4f}")

    joblib.dump(model, 'transformer_solar_model.pkl')
    print("\n[✓] Exported 'transformer_solar_model.pkl'")


if __name__ == '__main__':
    df = fetch_and_engineer_features(DATASET_URL)
    train_solar_model(df)
